### ISSUE TITLE
bitcoinfees.earn.com API is giving bad data on fees

### ISSUE THREAD

**Issue by bretton** [greatwolf/KKClient#5]
bitcoinfees.earn.com API is giving bad data on fees

Problem: `url: 'https://bitcoinfees.earn.com/api/v1/fees/recommended',` is old data and incorrect fees for current market conditions on 20 April 2021.

Rather use a new provider and configure for `url: 'https://mempool.space/api/v1/fees/recommended',` (from https://mempool.space/api)

**Comment by greatwolf** [comment]
Thanks for suggestion. I'll add that to the bitcoin fee service list as a possible alternative. At the moment it's currently set to use https://btc-fee.net which seems to give comparable estimates. They had some dns lookup issues about a week ago but it seem to be resolved now.
