### ISSUE TITLE
Sending bug

### ISSUE THREAD

**Issue by kroese** [greatwolf/KKClient#9]
I'm a long-time user of this client, thanks for it, but suddenly I've run into a (new?) issue.

When I go to my main BTC account, there was also a very small Bitcoin Gold balance displayed. The problem is that now when I try to send BTC it will not send the transaction because it thinks its above my balance, which is false. When I click the 'Send Maximum' button it shows the balance of the Bitcoin Gold and not the BTC. So this bug is causing the BTC and BTG balance to be swapped, and thus prevents me from sending BTC.

In order to solve this issue, I tried transferring all Bitcoin Gold to another wallet. But after that the Bitcoin Gold balance just displays 0 (zero), and the maximum BTC I can send is also 0 now. So this didnt help at all.

In the account overview screen my BTC balance is displayed correct, and also in the header of the sending page. So it seems just the maximum variabele that gets set incorrectly.

**Comment by greatwolf** [comment]
After some testing and debugging, I'm able to reproduce the problem. It seems to be a CORS issue, when sending btc, kkclient tries to estimate the current fee using blkhub.net(which is just a mirror of btc-fee.net).

I forgot to add it to the permissions section of the `manifest.json` so when the query is made it gets rejected by the browser causing the extension to just return 0 value to the frontend. A quick simple fix is to edit `manifest.json` and add this in the permissions section:

    "permissions":
    [
      "https://blkhub.net/*",
      "https://shapeshift.io/*",
      "https://*.trezor.io/api/*
      ...

Then just reload the extension so the changes take effect.

Extra note, you can change which fee estimating service to use in `config.js` look for `selectedFeeService` field. The original keepkey extension used `earn.com`, `coinquery.com` and `blockcypher.com` but I found them to be too overly aggressive often overpaying unnecessarily.

I added `btc-fee.net` and `blkhub.net` as an alternative for a more sane fee estimate but forgot to give extension permission to query those sites.

**Comment by kroese** [comment]
Thanks for your investigation, this fixed the issue for me indeed. Maybe the error handling when the BTC fee cannot be retrieved can also be a bit improved, because the current one (where it takes the values of an unrelated sub-account) seems a bit risky. For example, if it sends the BTC TX using the BTG fee values (like it did with the Max value) when blkhub is down, it can result in large losses.

**Comment by MarkB-UK** [comment]
Had the same problem myself and was pulling my hair out until I saw this post.

The blkhub added to permissions fixed everything. 

Thanks GW for keeping this up to date and all the improvements, much appreciated.

**Comment by greatwolf** [comment]
you welcome.
